# Site
name: "Сайт Вячеслава Романькова"
description: "Преподавателя креативного программирования"
meta_description: "Креативное программирование для всех"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'vrom1990-ru'
permalink: /:title/

# Authors
authors:
  vrom1990:
    name: Вячеслав Романьков
    display_name: Вячеслав Романьков
    gravatar: 3d19de0392a300c8908d2ddf90d72322
    email: mail@vrom1990.ru
    web: https://vrom1990.ru
    twitter: https://twitter.com/vrom1990
    description: "Преподаватель творческого программирования в Креайтивика"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
